REVOKE ALL ON FUNCTION public.bootstrap_account(uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ensure_fixed_admin(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ensure_fixed_admin_trg() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.protect_fixed_admin_role() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_fixed_admin(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_fixed_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bootstrap_account(uuid, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_fixed_admin(uuid) TO service_role;