ALTER FUNCTION public.fixed_admin_email() SET search_path = public;
REVOKE ALL ON FUNCTION public.bootstrap_account(uuid, text, text) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.ensure_fixed_admin(uuid) FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.ensure_fixed_admin_trg() FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.protect_fixed_admin_role() FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.is_fixed_admin(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM anon;
REVOKE ALL ON FUNCTION public.fixed_admin_email() FROM anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_fixed_admin(uuid) TO authenticated;